# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ase\PycharmProjects\kmp\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1018, 441)
        Form.setStyleSheet("*{\n"
"font-size: 12px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(223, 223, 223);\n"
"}\n"
"QPushButton{\n"
"min-height: 25px;\n"
"border-style: solid;\n"
"background-color: white;\n"
"border-width:1px;\n"
"border-radius:0px;\n"
"border-color: purple;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: white;\n"
"    width: 7px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background: #32CC99;\n"
"    min-height: 0px;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    background: #32CC99;\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    background: #32CC99;\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: white;\n"
"    height: 7px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: #32CC99;\n"
"    min-width: 0px;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    background: #32CC99;\n"
"    width: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    background: #32CC99;\n"
"    width: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"\n"
"")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.group_box = QtWidgets.QGroupBox(Form)
        self.group_box.setObjectName("group_box")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.group_box)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.group_box)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.start_story_ui = QtWidgets.QSpinBox(self.group_box)
        self.start_story_ui.setMinimumSize(QtCore.QSize(0, 25))
        self.start_story_ui.setMinimum(1)
        self.start_story_ui.setMaximum(100000)
        self.start_story_ui.setObjectName("start_story_ui")
        self.horizontalLayout.addWidget(self.start_story_ui)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.group_box)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.end_story_ui = QtWidgets.QSpinBox(self.group_box)
        self.end_story_ui.setMinimumSize(QtCore.QSize(0, 25))
        self.end_story_ui.setMinimum(1)
        self.end_story_ui.setMaximum(100000)
        self.end_story_ui.setObjectName("end_story_ui")
        self.horizontalLayout_2.addWidget(self.end_story_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_3 = QtWidgets.QLabel(self.group_box)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_8.addWidget(self.label_3)
        self.count_threads_ui = QtWidgets.QSpinBox(self.group_box)
        self.count_threads_ui.setMinimumSize(QtCore.QSize(0, 25))
        self.count_threads_ui.setMinimum(1)
        self.count_threads_ui.setMaximum(1000)
        self.count_threads_ui.setObjectName("count_threads_ui")
        self.horizontalLayout_8.addWidget(self.count_threads_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.load_data_from_net_ui = QtWidgets.QPushButton(self.group_box)
        self.load_data_from_net_ui.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.load_data_from_net_ui.setObjectName("load_data_from_net_ui")
        self.horizontalLayout_3.addWidget(self.load_data_from_net_ui)
        self.save_logs_ui = QtWidgets.QPushButton(self.group_box)
        self.save_logs_ui.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_logs_ui.setObjectName("save_logs_ui")
        self.horizontalLayout_3.addWidget(self.save_logs_ui)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.progress_bar_ui = QtWidgets.QProgressBar(self.group_box)
        self.progress_bar_ui.setProperty("value", 0)
        self.progress_bar_ui.setTextVisible(True)
        self.progress_bar_ui.setObjectName("progress_bar_ui")
        self.verticalLayout.addWidget(self.progress_bar_ui)
        self.text_browser_ui = QtWidgets.QTextBrowser(self.group_box)
        self.text_browser_ui.setObjectName("text_browser_ui")
        self.verticalLayout.addWidget(self.text_browser_ui)
        self.verticalLayout_2.addWidget(self.group_box)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.keywords_ui = QtWidgets.QTextEdit(self.groupBox_2)
        self.keywords_ui.setObjectName("keywords_ui")
        self.horizontalLayout_4.addWidget(self.keywords_ui)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.all_keywords_ui = QtWidgets.QCheckBox(self.groupBox_2)
        self.all_keywords_ui.setObjectName("all_keywords_ui")
        self.verticalLayout_4.addWidget(self.all_keywords_ui)
        self.result_text_box_ui = QtWidgets.QTextEdit(self.groupBox_2)
        self.result_text_box_ui.setObjectName("result_text_box_ui")
        self.verticalLayout_4.addWidget(self.result_text_box_ui)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.start_analysis_ui = QtWidgets.QPushButton(self.groupBox_2)
        self.start_analysis_ui.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_analysis_ui.setObjectName("start_analysis_ui")
        self.horizontalLayout_6.addWidget(self.start_analysis_ui)
        self.save_story_ui = QtWidgets.QPushButton(self.groupBox_2)
        self.save_story_ui.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_story_ui.setObjectName("save_story_ui")
        self.horizontalLayout_6.addWidget(self.save_story_ui)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.group_box.setTitle(_translate("Form", "Начальные значения"))
        self.label.setText(_translate("Form", "Начльная история:"))
        self.label_2.setText(_translate("Form", "Конечная история:"))
        self.label_3.setText(_translate("Form", "Количество потоков:"))
        self.load_data_from_net_ui.setText(_translate("Form", "Считать данные"))
        self.save_logs_ui.setText(_translate("Form", "Сохранить логи"))
        self.groupBox_2.setTitle(_translate("Form", "Анализ"))
        self.label_4.setText(_translate("Form", "Введите ключевые слова"))
        self.all_keywords_ui.setText(_translate("Form", "Наличие всех ключевых слов"))
        self.start_analysis_ui.setText(_translate("Form", "Начать анализ"))
        self.save_story_ui.setText(_translate("Form", "Сохранить истории"))
